[2024-12-19T10:50:25.076+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T10:50:25.104+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_insert_all_countries_news.fetch_and_insert_news_all_countries manual__2024-12-19T10:50:22.550379+00:00 [queued]>
[2024-12-19T10:50:25.118+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_insert_all_countries_news.fetch_and_insert_news_all_countries manual__2024-12-19T10:50:22.550379+00:00 [queued]>
[2024-12-19T10:50:25.119+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-19T10:50:25.141+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_insert_news_all_countries> on 2024-12-19 10:50:22.550379+00:00
[2024-12-19T10:50:25.151+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4917) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T10:50:25.153+0000] {standard_task_runner.py:72} INFO - Started process 4919 to run task
[2024-12-19T10:50:25.154+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_insert_all_countries_news', 'fetch_and_insert_news_all_countries', 'manual__2024-12-19T10:50:22.550379+00:00', '--job-id', '2602', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_connector_dag.py', '--cfg-path', '/tmp/tmpk2qxomiy']
[2024-12-19T10:50:25.158+0000] {standard_task_runner.py:105} INFO - Job 2602: Subtask fetch_and_insert_news_all_countries
[2024-12-19T10:50:25.228+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_insert_all_countries_news.fetch_and_insert_news_all_countries manual__2024-12-19T10:50:22.550379+00:00 [running]> on host 8348eb091483
[2024-12-19T10:50:25.376+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='srush' AIRFLOW_CTX_DAG_ID='fetch_and_insert_all_countries_news' AIRFLOW_CTX_TASK_ID='fetch_and_insert_news_all_countries' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T10:50:22.550379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T10:50:22.550379+00:00'
[2024-12-19T10:50:25.378+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T10:50:25.422+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2024-12-19T10:50:25.424+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-12-19T10:50:25.426+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2024-12-19T10:50:25.427+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-19T10:50:25.870+0000] {logging_mixin.py:190} INFO - Processing news for country: CH
[2024-12-19T10:50:27.873+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-03-10 to 2020-03-11 for CH...
[2024-12-19T10:50:28.755+0000] {logging_mixin.py:190} INFO - Error fetching data from 2020-03-10 to 2024-12-18: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-19T10:50:30.757+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-03-11 to 2020-03-12 for CH...
[2024-12-19T10:50:31.626+0000] {logging_mixin.py:190} INFO - Error fetching data from 2020-03-10 to 2024-12-18: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-19T10:50:33.628+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-03-12 to 2020-03-13 for CH...
[2024-12-19T10:50:34.472+0000] {logging_mixin.py:190} INFO - Error fetching data from 2020-03-10 to 2024-12-18: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-19T10:50:36.474+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-03-13 to 2020-03-14 for CH...
[2024-12-19T10:50:37.337+0000] {logging_mixin.py:190} INFO - Error fetching data from 2020-03-10 to 2024-12-18: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-19T10:50:39.339+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-03-14 to 2020-03-15 for CH...
[2024-12-19T10:50:40.157+0000] {logging_mixin.py:190} INFO - Error fetching data from 2020-03-10 to 2024-12-18: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-19T10:50:42.158+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-03-15 to 2020-03-16 for CH...
[2024-12-19T10:50:43.047+0000] {logging_mixin.py:190} INFO - Error fetching data from 2020-03-10 to 2024-12-18: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-19T10:50:45.049+0000] {logging_mixin.py:190} INFO - Fetching news from 2020-03-16 to 2020-03-17 for CH...
[2024-12-19T10:50:45.440+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-19T10:50:45.442+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-19T10:50:45.445+0000] {process_utils.py:132} INFO - Sending 15 to group 4919. PIDs of all processes in the group: [4919]
[2024-12-19T10:50:45.446+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 4919
[2024-12-19T10:50:45.447+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-19T10:50:45.449+0000] {connection.py:789} INFO - closed
[2024-12-19T10:50:45.564+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2024-12-19T10:50:45.617+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/snowflake_connector_dag.py", line 58, in fetch_and_insert_news_for_countries
    articles = gd.article_search(filters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gdeltdoc/api_client.py", line 79, in article_search
    articles = self._query("artlist", filters.query_string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gdeltdoc/api_client.py", line 155, in _query
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-19T10:50:45.636+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_insert_all_countries_news, task_id=fetch_and_insert_news_all_countries, run_id=manual__2024-12-19T10:50:22.550379+00:00, execution_date=20241219T105022, start_date=20241219T105025, end_date=20241219T105045
[2024-12-19T10:50:45.662+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T10:50:45.741+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=4919, status='terminated', exitcode=2, started='10:50:24') (4919) terminated with exit code 2
