[2024-12-20T05:26:03.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-20T05:26:03.058+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_insert_all_countries_news_1.fetch_and_insert_news_all_countries manual__2024-12-20T04:58:48.223168+00:00 [queued]>
[2024-12-20T05:26:03.073+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_insert_all_countries_news_1.fetch_and_insert_news_all_countries manual__2024-12-20T04:58:48.223168+00:00 [queued]>
[2024-12-20T05:26:03.075+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-20T05:26:03.099+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_insert_news_all_countries> on 2024-12-20 04:58:48.223168+00:00
[2024-12-20T05:26:03.111+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13978) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-20T05:26:03.114+0000] {standard_task_runner.py:72} INFO - Started process 13980 to run task
[2024-12-20T05:26:03.114+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_insert_all_countries_news_1', 'fetch_and_insert_news_all_countries', 'manual__2024-12-20T04:58:48.223168+00:00', '--job-id', '2622', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_connector_dag.py', '--cfg-path', '/tmp/tmp5iqedev_']
[2024-12-20T05:26:03.118+0000] {standard_task_runner.py:105} INFO - Job 2622: Subtask fetch_and_insert_news_all_countries
[2024-12-20T05:26:03.195+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_insert_all_countries_news_1.fetch_and_insert_news_all_countries manual__2024-12-20T04:58:48.223168+00:00 [running]> on host 7b4c45f22bd5
[2024-12-20T05:26:03.347+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='srush' AIRFLOW_CTX_DAG_ID='fetch_and_insert_all_countries_news_1' AIRFLOW_CTX_TASK_ID='fetch_and_insert_news_all_countries' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T04:58:48.223168+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T04:58:48.223168+00:00'
[2024-12-20T05:26:03.350+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-20T05:26:03.396+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2024-12-20T05:26:03.398+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-12-20T05:26:03.401+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2024-12-20T05:26:03.402+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-20T05:26:04.223+0000] {logging_mixin.py:190} INFO - Processing news for country: CH
[2024-12-20T05:26:09.227+0000] {logging_mixin.py:190} INFO - Fetching news from 2023-09-08 to 2023-09-09 for CH...
[2024-12-20T05:26:11.833+0000] {logging_mixin.py:190} INFO - Inserted 250 articles into Snowflake table 'DEMO_NEWS' for CH.
[2024-12-20T05:26:16.835+0000] {logging_mixin.py:190} INFO - Fetching news from 2023-09-09 to 2023-09-10 for CH...
[2024-12-20T05:26:20.502+0000] {logging_mixin.py:190} INFO - Error fetching data from 2023-09-08 to 2024-12-19: 'ValueError' object has no attribute 'pos'
[2024-12-20T05:26:23.402+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-20T05:26:23.404+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-20T05:26:23.406+0000] {process_utils.py:132} INFO - Sending 15 to group 13980. PIDs of all processes in the group: [13980]
[2024-12-20T05:26:23.407+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 13980
[2024-12-20T05:26:23.407+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-20T05:26:23.409+0000] {connection.py:789} INFO - closed
[2024-12-20T05:26:23.438+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2024-12-20T05:26:23.505+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-20T05:26:23.540+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=13980, status='terminated', exitcode=0, started='05:26:02') (13980) terminated with exit code 0
