[2024-12-17T10:19:01.394+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-17T10:19:01.501+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task scheduled__2024-12-16T00:48:00+00:00 [queued]>
[2024-12-17T10:19:01.568+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task scheduled__2024-12-16T00:48:00+00:00 [queued]>
[2024-12-17T10:19:01.576+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-17T10:19:01.892+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2024-12-16 00:48:00+00:00
[2024-12-17T10:19:01.907+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1876) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-17T10:19:01.922+0000] {standard_task_runner.py:72} INFO - Started process 1907 to run task
[2024-12-17T10:19:01.924+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'second_task', 'scheduled__2024-12-16T00:48:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpeekf6z2y']
[2024-12-17T10:19:01.937+0000] {standard_task_runner.py:105} INFO - Job 185: Subtask second_task
[2024-12-17T10:19:02.207+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v3.second_task scheduled__2024-12-16T00:48:00+00:00 [running]> on host 8348eb091483
[2024-12-17T10:19:02.671+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='srush' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T00:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T00:48:00+00:00'
[2024-12-17T10:19:02.673+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-17T10:19:02.747+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-17T10:19:02.764+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo task2 runs after task1']
[2024-12-17T10:19:02.856+0000] {subprocess.py:99} INFO - Output:
[2024-12-17T10:19:02.862+0000] {subprocess.py:106} INFO - task2 runs after task1
[2024-12-17T10:19:02.868+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-17T10:19:02.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-17T10:19:02.996+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v3, task_id=second_task, run_id=scheduled__2024-12-16T00:48:00+00:00, execution_date=20241216T004800, start_date=20241217T101901, end_date=20241217T101902
[2024-12-17T10:19:03.332+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-17T10:19:03.478+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-17T10:19:03.518+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
